server:
  port: 8083

spring:
  application:
    name: InvoiceManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/organization-management
    username: karlo
    password: lozinka
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
  profiles:
    active: default

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    to-fiscalization: fiscalization.queue.to
    fiscalization-result: fiscalization.queue.result
  routing-keys:
    internal-to-fiscalization: internal.to-fiscalization.routing-key
    internal-fiscalization-result: internal.fiscalization-result.routing-key