server:
  port: 8083

spring:
  application:
    name: InvoiceManagement
  datasource:
    url: jdbc:postgresql://postgres:5432/organization-management
    username: karlo
    password: karlo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672