apiVersion: v1
kind: Service
metadata:
  name: invoice-management
spec:
  selector:
    app: invoice-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
  type: LoadBalancer