apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiscalization
  labels:
    app: fiscalization
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fiscalization
  template:
    metadata:
      name: fiscalization
      labels:
        app: fiscalization
    spec:
      containers:
        - name: fiscalization
          image: svudec/fiscalizationnetcorewebapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: kube
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
