apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiscalization-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: "192.168.49.2.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1/invoice/(.*)"
        backend:
          service:
            name: invoice-management
            port:
              number: 80
      - pathType: Prefix
        path: "/api/v1/catalog/(.*)"
        backend:
          service:
            name: catalog-management
            port:
              number: 80