apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiscalization-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/v1/invoice"
        backend:
          service:
            name: invoice-management
            port:
              number: 8080
      - pathType: Prefix
        path: "/api/v1/catalog"
        backend:
          service:
            name: catalog-management
            port:
              number: 8080
