server:
  port: 8082

spring:
  application:
    name: FiscalizationService
  profiles:
    active: default
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    fiscalization: fiscalization.queue
  routing-keys:
    internal-fiscalization: internal.fiscalization.routing-key