apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fiscalization-scaledobject
  labels:
    deploymentName: fiscalization
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiscalization
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://rabbitmq.default.svc.cluster.local:5672/
      mode: QueueLength
      value: "1"
      queueName: "fiscalization.queue.to"
