server:
  port: 8080

spring:
  application:
    name: CatalogManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/organization-management
    username: karlo
    password: lozinka
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: default