server:
  port: 8081

spring:
  application:
    name: CatalogManagement
  datasource:
    url: jdbc:postgresql://postgres:5432/catalog-management
    username: karlo
    password: karlo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true