apiVersion: v1
kind: Service
metadata:
  name: catalog-management
spec:
  selector:
    app: catalog-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: LoadBalancer